### ISSUE TITLE
bad leak

### ISSUE THREAD

**Issue by doctor-swag** [B2H990/Raion#1]
Where is the Anti-0x22, Anti-Babbaj, Anti-FitMC, Anti-John200410. I wanted this stuff. 0/10 leak ok!

**Comment by JohnShiozo** [comment]
true

**Comment by B2H990** [comment]
True I should have remapped the entire source code... my bad

**Comment by doctor-swag** [comment]
Yes I wanted to paste anti-0x22, and all of the sexc anti-dump, very bad leak! pls do better next time thx
